const initialView = document.body.dataset.view || 'events';
const state = { view: initialView, page: 1, q: '', filterA: 'all', filterB: initialView === 'mentions' ? 'latest' : 'all', assertion: 'all' };
const mentionDetails = new Map();
const config = {
  events: { placeholder: '搜索事件 ID、事件名称、定义或路径', a: [['all','全部范围'],['company','公司事件'],['industry','行业事件']], b: [['all','全部层级'],['1','一级事件'],['2','二级事件'],['3','三级事件']] },
  routes: { placeholder: '搜索新闻标题、来源、输入行 ID 或事件 ID', a: [['all','全部路由状态'],['matched','已路由'],['trash','已丢弃']], b: [] },
  mentions: { placeholder: '搜索提取 ID、事件 ID、新闻标题、来源或事件名称', a: [['all','全部校验结果'],['true','有效匹配'],['false','待复核 / 不匹配']], b: [['latest','最新追加优先'],['forward','从文件开头浏览']] }
};
const $ = s => document.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
function optionList(el, rows, selected) { el.innerHTML = rows.map(([v,t]) => `<option value="${v}" ${v === selected ? 'selected':''}>${t}</option>`).join(''); el.style.display = rows.length ? '' : 'none'; }
function setupControls(){ const c=config[state.view]; $('#search').placeholder=c.placeholder; optionList($('#filter-a'),c.a,state.filterA); optionList($('#filter-b'),c.b,state.filterB); let assertion=document.querySelector('#filter-c'); if(state.view==='mentions'){if(!assertion){assertion=document.createElement('select');assertion.id='filter-c';$('#filter-b').after(assertion);assertion.onchange=e=>{state.assertion=e.target.value;state.page=1;load()}} optionList(assertion,[['all','全部断言状态'],['fact','事实（fact）'],['plan','计划（plan）'],['prediction','预测（prediction）'],['opinion','观点（opinion）'],['rumor','传闻（rumor）'],['missing','未标注']],state.assertion)}else if(assertion){assertion.style.display='none'} }
function chip(text, cls=''){ return `<span class="tag ${cls}">${esc(text)}</span>`; }
function eventCard(x){ return `<article class="card" data-id="${esc(x.event_id)}"><div class="card-head"><span class="id">${esc(x.event_id)}</span>${chip(x.scope === 'company' ? '公司事件':'行业事件')}</div><h3>${esc(x.event_name)}</h3><div class="path">${esc(x.source_path)}</div><div class="meta"><span>第 ${esc(x.level)} 层</span><span>${x.children.length} 个子事件</span></div><p class="preview">${esc(x.definition)}</p><p class="criteria"><b>纳入：</b>${esc((x.inclusion_criteria||[]).slice(0,2).join('；') || '—')}</p></article>`; }
function eventMiniCard(x){return `<div class="route-event"><span class="id">${esc(x.event_id)}</span><div><b>${esc(x.event_name)}</b><small>${esc(x.source_path)}</small></div></div>`}
function routeCard(x){ const good=x.route_status==='matched', mapped=(x.routed_events||[]).map(eventMiniCard).join(''); return `<article class="card" data-id="${esc(x.input_row_id)}"><div class="card-head"><span class="id">${esc(x.input_row_id)}</span>${chip(good?'已路由':'已丢弃',good?'good':'bad')}</div><h3>${esc(x.article_title || '未命名新闻')}</h3><div class="meta"><span>${esc(x.article_source || '未知来源')}</span><span>${esc(x.article_publish_time || '无发布时间')}</span></div>${mapped?`<div class="route-events"><label>路由事件卡</label>${mapped}</div>`:''}${x.trash_reason?`<div class="path">原因：${esc(x.trash_reason)}</div>`:''}<p class="preview">${esc(x.content_preview)}</p></article>`; }
function entityLabel(x){return x?.name?`${x.name}${x.entity_type?`（${x.entity_type}）`:''}${x.role?` · ${x.role}`:''}`:''}
function timeLabel(x){return x?.raw_text||x?.start_time||''}
function mentionCard(x){ mentionDetails.set(x.mention_id,x); const good=x.pair_valid===true, scope=x.scope==='company'?'公司事件':x.scope==='industry'?'行业事件':x.scope||'事件', s=x.extraction||{}, anchor=entityLabel(s.anchor_entity), times=(s.event_times||[]).slice(0,2).map(timeLabel).filter(Boolean), entities=(s.related_entities||[]).slice(0,3).map(entityLabel).filter(Boolean); return `<article class="card mention-card" data-id="${esc(x.mention_id)}"><div class="card-head"><span class="id">${esc(x.mention_id)}</span>${chip(good?'有效匹配':'待复核',good?'good':'bad')}</div>${s.event_fact?`<section class="fact-focus"><label>核心事件事实</label><strong>${esc(s.event_fact)}</strong></section>`:''}<div class="mention-found"><label>提取到的事件</label><h3>${esc(x.event_name || x.event_id)}</h3><div class="path">${esc(x.event_id)} · ${esc(x.source_path)}</div><div class="meta"><span>${esc(scope)}</span><span>第 ${esc(x.level || '—')} 层</span></div><p>${esc(x.event_definition || '未提供事件定义。')}</p></div>${anchor||times.length||entities.length||s.impact_direction?`<div class="extraction-brief">${anchor?`<span><b>主体</b>${esc(anchor)}</span>`:''}${times.length?`<span><b>时间</b>${esc(times.join('；'))}</span>`:''}${entities.length?`<span><b>关联方</b>${esc(entities.join('；'))}</span>`:''}${s.impact_direction?`<span class="impact ${esc(s.impact_direction)}"><b>影响</b>${esc(s.impact_direction)}</span>`:''}</div>`:''}<div class="mention-source"><label>来源新闻</label><b>${esc(x.article_title || '未命名新闻')}</b><span>${esc(x.article_source || '未知来源')} · ${esc(x.publication_time || '无发布时间')}</span></div>${x.invalid_reason?`<div class="path">校验：${esc(x.invalid_reason)}</div>`:''}<p class="preview">${esc(x.content_preview)}</p></article>`; }
function params(){ let p=new URLSearchParams({kind:state.view,page:state.page,size:24,q:state.q}); if(state.view==='events'){p.set('scope',state.filterA);p.set('level',state.filterB)} if(state.view==='routes')p.set('status',state.filterA); if(state.view==='mentions'){p.set('valid',state.filterA);p.set('order',state.filterB);p.set('assertion',state.assertion)} return p; }
async function load(){ const results=$('#results'); results.innerHTML='<div class="empty"><div>◌</div><p>正在查询数据…</p></div>'; const response=await fetch('/api/query?'+params()); const data=await response.json(); if(!response.ok) throw new Error(data.error||'查询失败'); const render={events:eventCard,routes:routeCard,mentions:mentionCard}[state.view]; results.innerHTML=data.items.length?data.items.map(render).join(''):$('#empty').innerHTML; $('#caption').textContent=state.view==='mentions'&&state.filterB==='latest'?'从 JSONL 文件末尾开始读取；点击“刷新数据”即可获取新追加记录。':`本页显示 ${data.items.length} 条记录。`; $('#page-state').textContent=`第 ${state.page} 页`; $('#prev').disabled=state.page===1; $('#next').disabled=!data.has_more; [...results.querySelectorAll('.card')].forEach(card=>card.onclick=()=>showDetail(card.dataset.id)); }
function line(label,value){return value?`<span>${esc(label)}：${esc(value)}</span>`:''}
function array(title,items){return items?.length?`<h4>${esc(title)}</h4><ul>${items.map(x=>`<li>${esc(typeof x==='string'?x:(x.event_name||JSON.stringify(x)))}</li>`).join('')}</ul>`:''}
async function showDetail(id){ const dialog=$('#detail'), body=$('#detail-body'); body.innerHTML='<p>正在载入完整记录…</p>'; dialog.showModal(); const res=await fetch(`/api/detail?kind=${state.view}&id=${encodeURIComponent(id)}`); const x=await res.json(); if(!res.ok){body.innerHTML='<p>无法读取该记录。</p>';return} const article=x.article||{}; if(state.view==='events'){const n=x.target_node||{};body.innerHTML=`<h2>${esc(n.event_name)}</h2><div class="detail-meta">${line('事件 ID',x.event_id)}${line('范围',x.scope)}${line('路径',x.source_path)}${line('层级',n.level)}</div><h4>定义</h4><p>${esc(n.definition||'—')}</p>${array('纳入标准',n.inclusion_criteria)}${array('排除标准',n.exclusion_criteria)}${array('子事件',x.children)}`;}else{const isMention=state.view==='mentions',card=x.event_card||{},node=card.target_node||{},routeCards=x.routed_event_cards||[];const fullRouteCards=routeCards.map(c=>`<section class="full-route-card"><div class="detail-meta">${line('事件 ID',c.event_id)}${line('范围',c.scope)}${line('层级',c.level)}</div><h3>${esc(c.event_name)}</h3><p class="detail-path">${esc(c.source_path)}</p><p>${esc(c.definition||'—')}</p>${array('纳入标准',c.inclusion_criteria)}</section>`).join('');const mentionedCard=isMention?`<h4>提取到的事件卡</h4><section class="full-route-card mention-detail-card"><div class="detail-meta">${line('事件 ID',x.event_id)}${line('范围',card.scope)}${line('层级',node.level)}</div><h3>${esc(node.event_name||x.event_id)}</h3><p class="detail-path">${esc(card.source_path||'—')}</p><p>${esc(node.definition||'—')}</p>${array('纳入标准',node.inclusion_criteria)}${array('排除标准',node.exclusion_criteria)}</section>`:'';body.innerHTML=`<h2>${esc(article.article_title||'未命名新闻')}</h2><div class="detail-meta">${line(isMention?'提取 ID':'输入行 ID',isMention?x.mention_id:x.input_row_id)}${line('状态',isMention?String(x.pair_valid):x.route_status)}${line('来源',article.article_source)}${line('发布时间',article.article_publish_time||x.publication_time)}</div>${mentionedCard}${fullRouteCards?`<h4>路由出的事件卡</h4>${fullRouteCards}`:''}${x.invalid_reason?`<h4>校验原因</h4><p>${esc(x.invalid_reason)}</p>`:''}${x.trash_reason?`<h4>丢弃原因</h4><p>${esc(x.trash_reason)}</p>`:''}<h4>新闻全文</h4><p class="detail-content">${esc(article.content||'—')}</p>`;} }
function structuredExtraction(s){if(!s)return '';const entity=x=>entityLabel(x),time=x=>`${x.time_type?`${x.time_type}：`:''}${timeLabel(x)}${x.start_time?` (${x.start_time}${x.end_time?` 至 ${x.end_time}`:''})`:''}`, items=(title,values)=>values?.length?`<section class="structured-section"><h4>${esc(title)}</h4><ul>${values.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></section>`:'';const anchor=entity(s.anchor_entity), related=(s.related_entities||[]).map(entity).filter(Boolean), times=(s.event_times||[]).map(time).filter(Boolean), evidence=s.evidence||[];if(!s.event_fact&&!anchor&&!related.length&&!times.length&&!s.impact_direction&&!s.impact_reason&&!s.assertion_status&&!s.claim_source&&!evidence.length)return '';return `<section class="structured-result"><p class="structured-title">结构化提取结果</p>${s.event_fact?`<div class="fact-focus"><label>核心事件事实</label><strong>${esc(s.event_fact)}</strong></div>`:''}${anchor?`<div class="structured-kv"><b>主体实体</b><span>${esc(anchor)}</span></div>`:''}${items('事件时间',times)}${items('关联实体',related)}${s.assertion_status?`<div class="structured-kv"><b>断言状态</b><span>${esc(s.assertion_status)}</span></div>`:''}${s.impact_direction?`<div class="structured-kv"><b>影响方向</b><span>${esc(s.impact_direction)}</span></div>`:''}${s.impact_reason?`<div class="structured-kv vertical"><b>影响依据</b><span>${esc(s.impact_reason)}</span></div>`:''}${s.claim_source?`<div class="structured-kv vertical"><b>主张来源</b><span>${esc([s.claim_source.type,s.claim_source.name,s.claim_source.raw_text].filter(Boolean).join(' · '))}</span></div>`:''}${items('证据文本',evidence)}</section>`}
const baseShowDetail = showDetail;
showDetail = async function(id){await baseShowDetail(id);if(state.view!=='mentions')return;const html=structuredExtraction(mentionDetails.get(id)?.extraction);const content=document.querySelector('#detail .detail-content');if(html&&content)content.insertAdjacentHTML('beforebegin',html);}
async function refreshSummary(){const r=await fetch('/api/summary');const d=await r.json();const nums=[d.counts.events,d.counts.routes,d.counts.mentions]; [...document.querySelectorAll('.metrics article b')].slice(0,3).forEach((el,i)=>el.textContent=nums[i].toLocaleString()); const live=document.querySelector('.live-metric span'); if(live)live.textContent=`最近文件更新时间：${d.mention_mtime}`;}
document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{state.view=btn.dataset.view;state.page=1;state.q='';state.filterA='all';state.filterB=state.view==='mentions'?'latest':'all';document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===btn));setupControls();load();});
$('#search').addEventListener('change',e=>{state.q=e.target.value;state.page=1;load()});$('#search').addEventListener('keydown',e=>{if(e.key==='Enter'){state.q=e.target.value;state.page=1;load()}});$('#filter-a').onchange=e=>{state.filterA=e.target.value;state.page=1;load()};$('#filter-b').onchange=e=>{state.filterB=e.target.value;state.page=1;load()};$('#reset').onclick=()=>{state.q='';state.filterA='all';state.filterB=state.view==='mentions'?'latest':'all';state.assertion='all';$('#search').value='';setupControls();state.page=1;load()};$('#refresh').onclick=()=>{refreshSummary();load()};$('#prev').onclick=()=>{if(state.page>1){state.page--;load()}};$('#next').onclick=()=>{state.page++;load()};$('#detail .close').onclick=()=>$('#detail').close();$('#detail').addEventListener('click',e=>{if(e.target===$('#detail'))$('#detail').close()});
setupControls();const assertionFilter=document.querySelector('#filter-c');if(assertionFilter)assertionFilter.onchange=e=>{state.assertion=e.target.value;state.page=1;load()};refreshSummary();load();
