const $ = s => document.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt = value => Number(value||0).toLocaleString('zh-CN');
const kinds={
  instances:{label:'聚合事件',placeholder:'搜索事件事实、实体、事件 ID、事件卡或领域',states:[['all','全部可信状态'],['confirmed','已确认'],['corroborated','多源印证'],['reported','已报道'],['unverified','待核验']]},
  reposts:{label:'同文传播',placeholder:'搜索标题、媒体或传播组 ID',states:[['all','全部首发状态'],['unique_earliest_observation','唯一最早观察'],['tied_earliest_observations','最早时间并列']]},
  reputation:{label:'领域信誉',placeholder:'搜索媒体或专业领域',states:[['all','全部档案'],['true','可发布档案'],['false','低样本档案']]},
  updates:{label:'信誉账本',placeholder:'搜索媒体、事件 ID、领域或更新 ID',states:[['all','全部更新'],['positive_evidence','已应用正向证据'],['pending_resolution','等待事件解决']]},
  claims:{label:'主张状态',placeholder:'搜索主张、主体、媒体或主张 ID',states:[['all','全部主张'],['unverified','未核实传闻'],['refuted_by_denial','已被否认'],['denial_observed_without_origin_claim','观察到澄清但缺原始主张']]},
  timelines:{label:'实体脉络',placeholder:'搜索公司、机构、人物或实体脉络 ID',states:[['all','全部脉络']]},
  alerts:{label:'动态预警',placeholder:'搜索预警事实、事件 ID 或预警 ID',states:[['all','全部预警'],['escalation','风险升级'],['rumor_watch','传闻观察']]}
};
const ids={instances:'event_instance_id',reposts:'repost_group_id',updates:'update_id',claims:'claim_id',timelines:'timeline_id',alerts:'alert_id'};
const params=new URLSearchParams(location.search);
const state={kind:kinds[params.get('view')]?params.get('view'):'instances',q:params.get('q')||'',filter:'all',domain:'all',page:1,hasMore:false};
let domains=[];
function chip(text,cls=''){return `<span class="intel-chip ${cls}">${esc(text)}</span>`}
function pct(value){return Math.round(Number(value||0)*100)}
function anchor(x){return x?.name||x||'—'}
function stateText(value){return ({confirmed:'已确认',corroborated:'多源印证',reported:'已报道',unverified:'待核验',positive_evidence:'正向证据',pending_resolution:'等待解决',unique_earliest_observation:'唯一最早观察',tied_earliest_observations:'最早并列',denial_observed_without_origin_claim:'已澄清/缺原始主张',refuted_by_denial:'已被否认'})[value]||value||'—'}
function setup(){
  document.querySelectorAll('#dataset-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.kind===state.kind));
  $('#intel-search').placeholder=kinds[state.kind].placeholder;$('#intel-search').value=state.q;
  $('#intel-state').innerHTML=kinds[state.kind].states.map(([v,t])=>`<option value="${v}" ${v===state.filter?'selected':''}>${t}</option>`).join('');
  const showDomain=['instances','reputation','updates'].includes(state.kind);
  $('#intel-domain').style.display=showDomain?'':'none';
  $('#intel-domain').innerHTML=`<option value="all">全部领域</option>`+domains.map(d=>`<option value="${esc(d.domain_name)}" ${d.domain_name===state.domain?'selected':''}>${esc(d.domain_name)}</option>`).join('');
  $('#query-hint').textContent=`当前数据集：${kinds[state.kind].label}`;
  history.replaceState(null,'',`intelligence.html?view=${state.kind}${state.q?`&q=${encodeURIComponent(state.q)}`:''}`);
}
function instanceCard(x){const score=pct(x.credibility_score);return `<article class="intel-card clickable" data-id="${esc(x.event_instance_id)}"><div class="intel-card-top"><code>${esc(x.event_instance_id)}</code>${chip(stateText(x.credibility_state),x.credibility_state)}</div><h3>${esc(x.canonical_fact)}</h3><div class="intel-meta"><span>${esc(anchor(x.anchor_entity))}</span><span>${esc(x.primary_event_name)}</span><span>${esc(x.event_date)}</span></div><div class="source-line"><b>${x.publisher_count||0}</b> 家媒体 · <b>${x.article_count||0}</b> 篇报道</div><div class="score-line"><span>可信度</span><i><em style="width:${score}%"></em></i><b>${score}</b></div></article>`}
function repostCard(x){const chain=(x.timeline||[]).map((n,i)=>`<span class="mini-hop ${i===0?'first':''}"><b>${esc(n.media_normalized)}</b><small>${esc((n.publish_time||'').slice(11,16))}</small></span>`).join('<i>›</i>');return `<article class="intel-card clickable" data-id="${esc(x.repost_group_id)}"><div class="intel-card-top"><code>${esc(x.repost_group_id)}</code>${chip(stateText(x.origin_status),'repost')}</div><h3>${esc(x.title)}</h3><div class="intel-meta"><span>${x.article_count} 篇</span><span>${x.media_count} 家媒体</span><span>${esc(x.first_publish_time)}</span></div><div class="mini-chain">${chain}</div><p class="card-warning">正文完全相同；时间顺序不等同于原创或直接转载证明。</p></article>`}
function reputationCard(x){const score=Number(x.resolved_reporting_score||0);return `<article class="intel-card reputation-card"><div class="intel-card-top"><code>${esc(x.domain)}</code>${chip(x.publishable?'样本充分':'低样本',x.publishable?'confirmed':'reported')}</div><div class="reputation-main"><div><h3>${esc(x.publisher_family)}</h3><p>${esc(x.domain)}</p><span>${x.resolved_event_count} 个已解决事件</span></div><div class="score-ring" style="--score:${score}"><b>${score.toFixed(1)}</b><small>表现分</small></div></div><div class="weight-grid"><span>原创权重 <b>${Number(x.original_weight).toFixed(2)}</b></span><span>同文后发权重 <b>${Number(x.copy_weight).toFixed(2)}</b></span></div><p class="card-warning">仅衡量该领域已解决事件中的报道表现，不代表媒体整体真实性。</p></article>`}
function updateCard(x){return `<article class="intel-card clickable" data-id="${esc(x.update_id)}"><div class="intel-card-top"><code>${esc(x.update_id)}</code>${chip(stateText(x.action),x.applied_to_score?'confirmed':'reported')}</div><h3>${esc(x.publisher_family)} · ${esc(x.domain)}</h3><div class="intel-meta"><span>${esc(x.event_instance_id)}</span><span>${esc(x.content_role)}</span><span>${esc(x.observed_at||'时间缺失')}</span></div><div class="delta"><span>正向增量</span><b>+${Number(x.positive_delta||0).toFixed(4)}</b><span>负向增量</span><b>-${Number(x.negative_delta||0).toFixed(4)}</b></div><p class="card-warning">${esc(x.reason)}</p></article>`}
function claimCard(x){return `<article class="intel-card clickable" data-id="${esc(x.claim_id)}"><div class="intel-card-top"><code>${esc(x.claim_id)}</code>${chip(stateText(x.state),x.state==='refuted_by_denial'?'alert':'reported')}</div><h3>${esc(x.claim_text)}</h3><div class="intel-meta"><span>${esc(x.anchor_entity)}</span><span>${esc(x.event_date)}</span><span>${esc(x.publisher_family||x.publisher)}</span></div>${x.denial_text?`<div class="denial-inline"><b>澄清/否认</b>${esc(x.denial_text)}</div>`:''}</article>`}
function timelineCard(x){return `<article class="intel-card clickable" data-id="${esc(x.timeline_id)}"><div class="intel-card-top"><code>${esc(x.timeline_id)}</code>${chip(`${x.event_count} 个事件`,'timeline')}</div><h3>${esc(x.anchor_entity)}</h3><div class="intel-meta"><span>${esc(x.start_date)} → ${esc(x.end_date)}</span><span>${x.distinct_event_type_count} 类事件</span><span>${x.distinct_date_count} 个日期</span></div><div class="timeline-preview"><i></i><i></i><i></i><i></i><i></i></div><p class="card-warning">点击查看该实体最多前 100 个事件节点。</p></article>`}
function alertCard(x){return `<article class="intel-card clickable alert-card" data-id="${esc(x.alert_id)}"><div class="intel-card-top"><code>${esc(x.alert_id)}</code>${chip(stateText(x.alert_type),'alert')}</div><div class="alert-score"><b>${pct(x.alert_score)}</b><span>预警分</span></div><h3>${esc(x.canonical_fact||x.event_instance_id)}</h3><div class="intel-meta"><span>${esc(x.event_date)}</span><span>${x.publisher_count||0} 家媒体</span><span>可信度 ${pct(x.credibility)}</span></div></article>`}
const renderers={instances:instanceCard,reposts:repostCard,reputation:reputationCard,updates:updateCard,claims:claimCard,timelines:timelineCard,alerts:alertCard};
async function load(){
  $('#intel-results').innerHTML='<div class="intel-empty">正在检索数据…</div>';
  const q=new URLSearchParams({kind:state.kind,page:state.page,size:18,q:state.q,state:state.filter,domain:state.domain});
  try{const response=await fetch('/api/intelligence/query?'+q);const data=await response.json();if(!response.ok)throw new Error(data.error||'查询失败');state.hasMore=data.has_more;$('#intel-results').innerHTML=data.items.length?data.items.map(renderers[state.kind]).join(''):'<div class="intel-empty"><b>没有匹配结果</b><span>请调整关键词或筛选条件。</span></div>';$('#result-caption').textContent=`本页显示 ${data.items.length} 条 · ${data.updated_at}`;$('#intel-page').textContent=`第 ${state.page} 页`;$('#intel-prev').disabled=state.page===1;$('#intel-next').disabled=!data.has_more;document.querySelectorAll('.intel-card.clickable').forEach(card=>card.onclick=()=>detail(card.dataset.id));}catch(error){$('#intel-results').innerHTML=`<div class="intel-empty error">${esc(error.message)}</div>`}}
function pretty(value){return esc(JSON.stringify(value,null,2))}
async function detail(id){const dialog=$('#intel-detail'),body=$('#intel-detail-body');dialog.showModal();body.innerHTML='<p>正在载入完整记录…</p>';const response=await fetch(`/api/intelligence/detail?kind=${state.kind}&id=${encodeURIComponent(id)}`);const x=await response.json();if(!response.ok){body.innerHTML='<p>无法读取记录。</p>';return}if(state.kind==='reposts'){body.innerHTML=`<p class="eyebrow">EXACT REPOST CHAIN</p><h2>${esc(x.title)}</h2><p class="detail-note">全文归一化后完全一致；最早观察不证明原创。</p><div class="detail-chain">${x.timeline.map((n,i)=>`<div><span>${i+1}</span><time>${esc(n.publish_time)}</time><b>${esc(n.media_normalized)}</b><p>${esc(n.title)}</p><small>相对首条 +${n.delay_from_first_minutes} 分钟</small></div>`).join('')}</div>`}else if(state.kind==='timelines'){body.innerHTML=`<p class="eyebrow">ENTITY TIMELINE</p><h2>${esc(x.anchor_entity)}</h2><div class="detail-meta"><span>${x.event_count} 个事件</span><span>${esc(x.start_date)} → ${esc(x.end_date)}</span></div><div class="detail-event-list">${(x.event_details||[]).map(n=>`<article><time>${esc(n.event_date)}</time><b>${esc(n.primary_event_name)}</b><p>${esc(n.canonical_fact)}</p><small>${n.publisher_count||0} 家媒体 · 可信度 ${pct(n.credibility_score)}</small></article>`).join('')}</div>`}else{body.innerHTML=`<p class="eyebrow">FULL RECORD</p><h2>${esc(id)}</h2><pre>${pretty(x)}</pre>`}}
async function init(){try{const r=await fetch('/api/showcase');const b=await r.json();domains=b.domain_taxonomy||[];$('#validation').textContent=(b.validation_status||'—').toUpperCase();$('#health-note').textContent=`关键错误 0 · LLM 调用 ${b.llm_calls}`;}catch{}setup();load()}
document.querySelectorAll('#dataset-tabs button').forEach(btn=>btn.onclick=()=>{state.kind=btn.dataset.kind;state.page=1;state.q='';state.filter='all';state.domain='all';setup();load()});
$('#intel-search').onkeydown=e=>{if(e.key==='Enter'){state.q=e.target.value.trim();state.page=1;setup();load()}};$('#intel-search').onchange=e=>{state.q=e.target.value.trim();state.page=1;setup();load()};
$('#intel-state').onchange=e=>{state.filter=e.target.value;state.page=1;load()};$('#intel-domain').onchange=e=>{state.domain=e.target.value;state.page=1;load()};$('#intel-reset').onclick=()=>{state.q='';state.filter='all';state.domain='all';state.page=1;setup();load()};$('#intel-refresh').onclick=load;$('#intel-prev').onclick=()=>{if(state.page>1){state.page--;load()}};$('#intel-next').onclick=()=>{if(state.hasMore){state.page++;load()}};$('#intel-detail .close').onclick=()=>$('#intel-detail').close();$('#intel-detail').onclick=e=>{if(e.target===$('#intel-detail'))$('#intel-detail').close()};init();
