const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let events = [], byId = new Map(), currentId = '';

function roots(){ return events.filter(x => x.is_root).sort((a,b) => a.event_id.localeCompare(b.event_id)); }
function childrenOf(x){ return (x.children || []).map(c => byId.get(c.event_id)).filter(Boolean).sort((a,b) => a.event_id.localeCompare(b.event_id)); }
function button(x){ return `<button class="tree-node ${x.event_id===currentId?'selected':''}" data-id="${esc(x.event_id)}"><span class="node-level l${x.level}">L${x.level}</span><span>${esc(x.event_name)}</span><code>${esc(x.event_id)}</code></button>`; }
function node(x, depth){ const kids = childrenOf(x); if(!kids.length) return `<div class="tree-leaf depth-${depth}">${button(x)}</div>`; return `<details class="tree-branch depth-${depth}" data-id="${esc(x.event_id)}"><summary>${button(x)}<em>${kids.length}</em></summary><div class="tree-kids"></div></details>`; }
function bind(container){ container.querySelectorAll('.tree-node').forEach(el => el.onclick = event => { event.stopPropagation(); show(el.dataset.id); }); container.querySelectorAll('.tree-branch').forEach(el => el.addEventListener('toggle', () => { if(el.open) renderChildren(el); })); }
function renderChildren(branch){ if(branch.dataset.rendered) return; const parent = byId.get(branch.dataset.id); const target = branch.querySelector('.tree-kids'); target.innerHTML = childrenOf(parent).map(x => node(x, Number(parent.level) + 1)).join(''); branch.dataset.rendered = 'true'; bind(target); }
function detailList(title, items){ return items?.length ? `<section><h4>${esc(title)}</h4><ul>${items.map(x => `<li>${esc(typeof x === 'string' ? x : (x.event_name || ''))}</li>`).join('')}</ul></section>` : ''; }
async function show(id){ currentId = id; document.querySelectorAll('.tree-node').forEach(x => x.classList.toggle('selected', x.dataset.id === id)); const panel = document.querySelector('#event-detail'); panel.innerHTML = '<div class="empty"><div>◌</div><p>正在读取事件卡…</p></div>'; const response = await fetch(`/api/detail?kind=events&id=${encodeURIComponent(id)}`); const card = await response.json(); if(!response.ok){ panel.innerHTML = '<div class="empty"><h3>事件卡读取失败</h3></div>'; return; } const n = card.target_node || {}; panel.innerHTML = `<div class="detail-top"><span class="id">${esc(card.event_id)}</span><span class="tag">${esc(card.scope==='company'?'公司事件':'行业事件')}</span></div><h2>${esc(n.event_name)}</h2><p class="detail-path">${esc(card.source_path)}</p><section><h4>事件定义</h4><p>${esc(n.definition || '—')}</p></section>${detailList('纳入标准', n.inclusion_criteria)}${detailList('排除标准', n.exclusion_criteria)}${detailList('下级事件', card.children)}${detailList('同级事件', card.siblings)}`; }
function searchTree(query){ const q = query.trim().toLowerCase(); if(!q){ document.querySelector('#tree').innerHTML = roots().map(x => node(x, 1)).join(''); bind(document.querySelector('#tree')); return; } const matches = x => [x.event_id,x.event_name,x.source_path].join(' ').toLowerCase().includes(q); const build = (x, depth) => { const kids = childrenOf(x).map(k => build(k, depth + 1)).filter(Boolean); if(!matches(x) && !kids.length) return ''; const own = `<div class="tree-leaf depth-${depth}">${button(x)}</div>`; return kids.length ? `<details class="tree-branch depth-${depth}" open><summary>${button(x)}<em>${kids.length}</em></summary><div class="tree-kids">${kids.join('')}</div></details>` : own; }; document.querySelector('#tree').innerHTML = roots().map(x => build(x, 1)).filter(Boolean).join('') || '<p class="no-tree">没有匹配的事件。</p>'; bind(document.querySelector('#tree')); }
fetch('/api/tree').then(r => r.json()).then(data => { events = data; byId = new Map(data.map(x => [x.event_id, x])); document.querySelector('#tree-caption').textContent = `共 ${data.length.toLocaleString()} 张事件卡片 · 初始仅加载一级节点，逐层展开`; searchTree(''); }).catch(() => document.querySelector('#tree-caption').textContent = '事件体系读取失败，请确认服务正在运行。');
document.querySelector('#tree-search').addEventListener('input', event => searchTree(event.target.value));
